import React from "react";

const Blog = () => {
  return (
    <div>
      <main className="pt-8 pb-16 lg:pt-16 lg:pb-24 bg-white dark:bg-gray-900 antialiased">
        <div className="flex justify-between px-4 mx-auto max-w-screen-xl ">
          <div className="mx-auto w-full max-w-2xl format format-sm sm:format-base lg:format-lg format-blue dark:format-invert">
            <header className="mb-4 lg:mb-6 not-format">
              <address className="flex items-center mb-6 not-italic">
                <div className="inline-flex items-center mr-3 text-sm text-gray-900 dark:text-white">
                  <img
                    className="mr-4 w-16 h-16 rounded-full"
                    src="https://flowbite.com/docs/images/people/profile-picture-2.jpg"
                    alt="Jese Leos"
                  />
                  <div>
                    <a
                      href="#"
                      rel="author"
                      className="text-xl font-bold text-gray-900 dark:text-white"
                    >
                      Kirill Rozov
                    </a>
                    <p className="text-base text-gray-500 dark:text-gray-400">
                      Graphic Designer, educator
                    </p>
                    <p className="text-base text-gray-500 dark:text-gray-400">
                      <time
                        pubdate
                        datetime="2022-02-08"
                        title="February 8th, 2022"
                      >
                        Feb. 8, 2022
                      </time>
                    </p>
                  </div>
                </div>
              </address>
              <h1 className="mb-4 text-3xl font-extrabold leading-tight text-gray-900 lg:mb-6 lg:text-4xl dark:text-white">
                Android Fragmentation state. Did Google fix it?
              </h1>
            </header>
            <div className=" space-y-5 justify-center items-center mb-2">
              <p>
                In Android 13 a new feature called Photo Picker appeared. It
                allows applications to access individual user photos and videos
                without giving them full access to the photo/video or the entire
                memory of the device. This is a good feature for limiting an
                application’s access to a user’s personal data. It was
                immediately announced that this feature would also work on
                Android 11 and newer (with support for Mainline updates), and
                later its support was added to all devices with Android 4.4 and
                above via Google Play Services.
              </p>
              <p>
                I immediately asked myself, why hasn’t it been done before? And
                the answer is simple — Android didn’t allow to implement this,
                because Google was struggling with fragmentation and working on
                the possibility of an independent update of Android, it became a
                reality.
              </p>
              <figure className=" text-center">
                <img
                  src="https://res.cloudinary.com/dunf6rko6/image/upload/v1708688153/dho7c8iv0o4ns4jza1yp.webp"
                  alt=""
                />
                <figcaption classNameName=" text-center">
                  Image generated by Kandinsky 2.2
                </figcaption>
              </figure>
            </div>

            <section className="not-format">
              <article className="p-6 text-base bg-white border-t border-gray-200 dark:border-gray-700 dark:bg-gray-900">
                <footer className="flex justify-between items-center mb-2">
                  <div className="flex items-center">
                    <p className="inline-flex items-center mr-3 font-semibold text-sm text-gray-900 dark:text-white">
                      <img
                        className="mr-2 w-6 h-6 rounded-full"
                        src="https://flowbite.com/docs/images/people/profile-picture-4.jpg"
                        alt="Helene Engels"
                      />
                      Helene Engels
                    </p>
                    <p className="text-sm text-gray-600 dark:text-gray-400">
                      <time
                        pubdate
                        datetime="2022-06-23"
                        title="June 23rd, 2022"
                      >
                        Jun. 23, 2022
                      </time>
                    </p>
                  </div>
                </footer>
                <p>
                  Thanks for sharing this. I do came from the Backend
                  development and explored some of the tools to design my Side
                  Projects.
                </p>
              </article>
            </section>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Blog;
